// <auto-generated />
using Hotels.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotels.API.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20230107182947_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotels.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Latutude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latutude = 44.892125,
                            Longitude = 13.805581800000001,
                            Name = "Adrion Aparthotel",
                            Price = 103m
                        },
                        new
                        {
                            Id = 2,
                            Latutude = 44.892125900000003,
                            Longitude = 13.826331100000001,
                            Name = "B&B Sonia",
                            Price = 56m
                        },
                        new
                        {
                            Id = 3,
                            Latutude = 44.892009299999998,
                            Longitude = 13.826331,
                            Name = "Crazy House Hostel",
                            Price = 53m
                        },
                        new
                        {
                            Id = 4,
                            Latutude = 44.8953402,
                            Longitude = 13.8200907,
                            Name = "Villa Brandestini",
                            Price = 217m
                        },
                        new
                        {
                            Id = 5,
                            Latutude = 44.898255800000001,
                            Longitude = 13.796201099999999,
                            Name = "Milan Hotel",
                            Price = 150m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
